### ISSUE TITLE
Specify the arguments to pass to main.py

### ISSUE THREAD

**Issue by jingyng** [YDYordanov/Few-shot-NLEs#1]
Hi, 
thank you for the interesting work. Could you specify which arguments should we pass for each of the experiments you ran in Table 2? There are many arguments in the main.py and I am not able to understand how to pass them correctly.

Thank you!
Best regards,

**Comment by YDYordanov** [comment]
Hi! Thank you for taking interest in my work! I will release those details in the coming weeks. The reason for delaying is that I am quite busy at the moment.

**Comment by YDYordanov** [comment]
Hi! I added some guidance in the Readme file on how to use main.py. I hope this helps. The experiment reproduction scripts are coming soon.

**Comment by YDYordanov** [comment]
Btw I have updated the data names and added some new data files, so please download/clone the newest library version and follow the new instructions. In particular, re-run "pip install -r requirements.txt" and run the new script "python download_and_process_data.py".

**Comment by YDYordanov** [comment]
I've just uploaded all model training scripts. The scripts to generate Table 3 will be ready in the coming days. Happy New Year!

**Comment by YDYordanov** [comment]
Hi! I have added additional instructions and scripts. Now it should be clear how to do it.
