### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'Data/e-WG/new_dev_nles_only.jsonl'

### ISSUE THREAD

**Issue by jingyng** [YDYordanov/Few-shot-NLEs#2]
When I am trying to run the ewg task, the error says there is no file of 'Data/e-WG/new_dev_nles_only.jsonl', and I couldn't generate from the code, could you please inform me how to get the missing files? Thank you!

**Comment by YDYordanov** [comment]
Hi! Thank you for taking interest in my project! I believe this should be "small-e-WinoGrande/WG_dev_50NLEs.jsonl". If I understand you correctly, the missing files you can get by clicking the three dataset links in the "Readme.md" file, by putting the files in their respective folders, and then by running the data processing scripts in those folders as described in the "Readme.md" file here.

**Comment by jingyng** [comment]
Hi thank you for the reply. 
Yes it is the right file, thanks again!
